name: Build and Publish Thanos Container
permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'thanos-*'

jobs:
  setup:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'thanos-')
    outputs:
      container: ${{ steps.extract.outputs.container }}
      revision: ${{ steps.extract.outputs.revision }}
      context: ${{ steps.versions.outputs.context }}
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract container, version and revision
        id: extract
        run: |
          TAG=${{ github.event.release.tag_name }}
          IFS='-' read -ra parts <<< "$TAG"
          CONTAINER=${parts[0]}
          if [ ${#parts[@]} -eq 3 ]; then
            VERSION=${parts[1]}
            REVISION=${parts[2]}
          else
            echo "Invalid tag format for Thanos. Expected: thanos-<version>-<revision>"
            exit 1
          fi
          echo "container=$CONTAINER" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "revision=$REVISION" >> $GITHUB_OUTPUT

      - name: Set context for Thanos
        id: versions
        run: |
          CONTEXT="docker/thanos"
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

  build:
    needs: setup
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ needs.setup.outputs.context }}
          push: true
          build-args: |
            THANOS_VERSION=${{ needs.setup.outputs.version }}
          tags: ghcr.io/${{ github.repository_owner }}/containers/${{ needs.setup.outputs.container }}:${{ needs.setup.outputs.version }}-${{ needs.setup.outputs.revision }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
